### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by MrRiverard** [Adkali/Subxenum#1]
┌──(root㉿localhost)-[/Subxenum]
└─# python3 Subxenum.py -domain https://mcpasd.k12.wi.us -word /Subdomain-wordlist.txt

 _____       _                                    
/  ___|     | | [use '-h' for more help]                                  
\ `--. _   _| |____  _____ _ __  _   _ _ __ ___   
 `--. \ | | | '_ \ \/ / _ \ '_ \| | | | '_ ` _ \  
/\__/ / |_| | |_) >  <  __/ | | | |_| | | | | | | 
\____/ \__,_|_.__/_/\_\___|_| |_|\__,_|_| |_| |_| 

 Adkali - SubDomain Enumerate T00l

    
Note: >> Continue without  -i('Whois') flag
Note: >> Continue without  -c('crt') flag
Note: >> Continue without  -s('sublist3r') flag
Continue run by /Subdomain-wordlist.txt? type y/n: y

[!]Please wait>>>

#################################################################

[+] >> Status: (INFO) Successful HTTP requests!
[+] >> Date and time: 2024-09-13 14:18:29.215111
[+] >> File loaded: (INFO) /Subdomain-wordlist.txt
[!] >> Warning: (INFO) File /Subdomain-wordlist.txt contains 13171 Subdomains words.
[?] >> Mode: (INFO) Starting enumerate subdomains on https://mcpasd.k12.wi.us, Please Wait...

---------------------------
Traceback (most recent call last):
  File "/Subxenum/Subxenum.py", line 223, in <module>
    url = f"http://{j}.{d[1]}"
                        ~^^^
IndexError: list index out of range
                                                                                                                                       
┌──(root㉿localhost)-[/Subxenum]
└─#

**Comment by Adkali** [comment]
Try using the unsecure protocol with "http" instead "https". Anyway, i will upgrade it soon as i finish previous projects. Thanks!

> ┌──(root㉿localhost)-[/Subxenum] └─# python3 Subxenum.py -domain https://mcpasd.k12.wi.us -word /Subdomain-wordlist.txt
> 
> / ___| | | [use '-h' for more help] \ `--. _ _| |____ _____ _ __ _ _ _ __ ___ `--. \ | | | '_ \ / / _ \ '_ | | | | '_ ` _ \ /__/ / |_| | |_) > < __/ | | | |_| | | | | | | ____/ __,_|_.**/_/__**|_| |_|__,_|_| |_| |_|
> 
> Adkali - SubDomain Enumerate T00l
> 
> Note: >> Continue without -i('Whois') flag Note: >> Continue without -c('crt') flag Note: >> Continue without -s('sublist3r') flag Continue run by /Subdomain-wordlist.txt? type y/n: y
> 
> [!]Please wait>>>
> 
> #################################################################
> 
> [+] >> Status: (INFO) Successful HTTP requests! [+] >> Date and time: 2024-09-13 14:18:29.215111 [+] >> File loaded: (INFO) /Subdomain-wordlist.txt [!] >> Warning: (INFO) File /Subdomain-wordlist.txt contains 13171 Subdomains words. [?] >> Mode: (INFO) Starting enumerate subdomains on https://mcpasd.k12.wi.us, Please Wait...
> 
> Traceback (most recent call last): File "/Subxenum/Subxenum.py", line 223, in url = f"http://{j}.{d[1]}" ~^^^ IndexError: list index out of range
> 
> ┌──(root㉿localhost)-[/Subxenum] └─#
